spring:
  application:
    name: webhook-managment
  config:
    activate:
      on-profile: dev


  data:
    mongodb:
      uri: mongodb://localhost:27017/spring-database
      database: spring-database

oms:
  baseURL: http://baseurl.com

AWS:
  ACCESS_KEY_ID: your_key
  SECRET_ACCESS_KEY: your_secret
  WEBHOOK_SQS_URL: https://sqs.us-east-1.amazonaws.com/366593783946/mamtha-test-queue
  REGION: "us-east-1"